##############################################################################
#############     Storage Path Parameters for all Platforms     ##############
##############################################################################

toggle:
  useCloud: azure
 
storagePathParams:
  redTeaming:
    secretName: grafyn-storage-secret
    s3:
      - s3_access_key_id
      - s3_secret_access_key
      - region = "us-east-1"
      - location = "grafyn-redteam-bucket"
    azureBlob:
      - blob-storage-account
      - blob-storage-key
      - location = "qa-grafyn"
      - path_prefix = "results/"


      
