##############################################################################
#############     Storage Path Parameters for all Platforms     ##############
##############################################################################

toggle:
  useCloud: aws
 
storagePathParams:
  redTeaming:
    secretName: grafyn-storage-redteam
    s3:
      - s3_access_key_id
      - s3_secret_access_key
      - region = "us-east-1"
    azureBlob:
      - storage-account
      - storage-key
